language: node_js
node_js:
- '12'
cache:
  directories:
  - "$HOME/.cache/yarn"
  - node_modules
script:
- cd ./backend
- yarn
- yarn build
- cd ../frontend
- yarn
- yarn build
notifications:
  slack:
    secure: KTnhYsnm4ghUBA6doygHHLBvLYaZ9KBqF0KTSL4N0ZVinBR/9ZXF/bLwW3h86AHKq/lwQJI40ZiTmPV81cH2i53BxGZ4SNfZ5Sql8zJOoN5+EbtAgAg2sxkYbE5gS9FxMDjmJexR2ROUldWbV3ZSPNC0gGuX/Hsw0tcztmAt3/tbDTF7bgy4ivOpnok9vLO46stw3jcqsP6KogUdkY/aYKGU1ZLvVA0g1M7T4fpbP8dCNOpychqzaI94+p0aYUp2G8jnotcAxatvssbEP+H5C9jCyOWiDXaQimrk+ALIqPnFrCoe6lerlf6UyIIAHtOcSV/Ld7pHA5j+L0bC0lfTZ6lxj7kqi7NE0GPXolePWvVhuLM7J6kGwesdLKZ6jAqoqVrn/oMxqwmwpdn91cT7FKiM8ZxHoG01jGm6a0R0LpJiAbNw7N63hgZXEsIFOzwnYrqT9OIbJeYU35P4GH4Z51jo13wBcAmZws5WsUjrr0I5hWmTxgYSbGG5oWC6vNtmTHlcq1AK3f2LL01qB8YTF5wQROl8+kk+P/ZLXPTc9q6Wh0lC+C6mkU0txKN0FGyM0gIuEI6rjp4fZKf3Jvtbw06gyjAsQiTwp3lnuMc+Ui3B/NuTHHjvARl9xxsprWqvEr+YkbDR35XK+zE/OHPeEMxY0YEdS+dc4z8FKTnMDc4=
